plugins/cck_field/calendar/calendar.php

In bootstrap, only btn doesn't work, I just added the class btn-default.

Add btn-default class in calendar button

---

libraries/cms/cck/dev.php

Auto add include if class does not exist

Fix missing include when validation is used as standalone (outside cck component)

---

administrator/components/com_cck/install/upgrades/2.6.0.sql

remove birthdate and birthplace from 2.6.0 update sql to allow 3.2.0 update sql to work
fixes #134

remove birthdate and birthplace from 2.6.0 update sql - fixes #134

---

plugins/cck_field/upload_file/upload_file.php
plugins/cck_field/upload_image/upload_image.php

When upload image/files is used a s field x, error in one image (e.g. due to size) breaks upload also for other images.
Fixes #101

fix error in one child breaking upload for others

---

plugins/cck_field/jform_tag/jform_tag.php

Joomla tries to load this class from wrong place as jpath_base resolves to administrator in backend..
Reference http://www.seblod.com/community/forums/fields-plug-ins/article-tags-in-combination-with-smart-search-error#post43135

load TagsHelperRuoute to prevent fatal error in backend

---

plugins/cck_field_typo/joomla_jgrid/joomla_jgrid.php

Fix 
An error has occurred.
500 JHtml contentadministrator not found. 
Error occurs in admin when Reordering is used together with featured as there are 2 static variables with name $loaded.

Fix JHtml error

---

administrator/components/com_cck/views/types/tmpl/default.php

Instead of template name php code is sent to javascript causing mod_security to scream..

Fix php code beeing output to javascript

---

libraries/cck/base/list/list.php
plugins/cck_storage_location/joomla_article/joomla_article.php

Fix auto redirect that redirects to url  `&amp` instead of &, causing problems with some servers
Added same change to other instances, this will only affect non-sef urls.
Reference
https://www.seblod.com/community/forums/lists-search-types/auto-redirection-url-issue

fix redirect with sef deactivated

---

plugins/cck_storage_location/joomla_user/classes/exporter.php

Latest Joomla has 2 new field that not registered in seblod user object export, i'll update the excluded field, and the problem is gone.
To All User: This kind of issue is related with core Joomla. If Joomla team decide to add/remove field in #__users table, this 'bug' will arise again. So hopefully, as community, if you happen upgrade joomla to newer version than 3.6.5, please check #__users and let us know if the team made changes on this table.

Fix Issue #365

---

plugins/cck_field/calendar/calendar.php

Fix issue with live values like now in search, also improve processing in form to get the same value submited for live and default and also prevent submitting value when value is emtpy (not set by either user/live/default)

Calendar - properly handle live/default values in form and search

---

plugins/cck_field/calendar/calendar.php

Running Seblod 3.15.0 and Joomla 3.8.2:
When I edit a form wich has a calendar field, not filled when it was submitted, has this value: "-0001-11-30".
Then, when we try to save the form, the following error appears:
Error: 0 - You either used wrong format or locale set by language file is not supported on your server - es_ES.utf8
The calendar field format is "Y-m-d", the storage format "Datetime" and its value is 0000-00-00 in the database (mysql date field format, not datetime format), then if we add: "or if date = 0000-00-00" the problem is fixed.
Thank you.

Avoid "Error: 0" when an empty date is edited

---

administrator/components/com_cck/install/install.sql

My JS code was getting truncated when saving so I have adjusted the datatype of the field to text instead of varchar(2048). See https://www.seblod.com/community/forums/fields-plug-ins/field-script-js-lines-limit for more details.

Change defaultvalue column to text datatype in cck_core_fields table

---

plugins/cck_field/jform_tag/jform_tag.php

An import can fail due to an empty tag title. This occurs if there is a trailing comma at the end of a list of tags supplied in an import file. If a tag to import is empty, skip it.

Avoid importing empty tag title

---

plugins/cck_field/jform_tag/jform_tag.php

White space around a tag name supplied in an import file (for example, if there is white space after a comma in a list of tags) may result in a tag not getting 'tagged' on the newly imported article, even if the tag already exists. This is because the tag field will attempt to create a new tag with the white space, but the alias that Joomla creates will collide with the existing tag, and the creation fails silently.
In `onCCK_FieldPrepareImport()`, before querying for an existing tag, or potentially creating a new tag, trim the whitespace around the tag name. This allows for a comma-separated list of tags to imported from an import file, using ", " (comma then space) as a separator.

Strip whitespace from imported tag title

---

plugins/cck_storage_location/joomla_article/joomla_article.php

In com_content router, when invoking JRoute on an article view, if just the article id is passed and not the full slug (id:alias), the component router adds the alias. This PR replicates this feature in Seblod article routing and it is important since when SEF is the default "id-alias", it should not be mandatory to include the alias in the RAW URL passed to the router since the alias may change in the future and that would produce a broken URL in Seblod with 404 Error.
This PR retrieve article alias from #__content and adds it to the article id if the alias is missing.

make article SEF routing independent from article alias

---

plugins/cck_field/upload_file/includes/afterstore.php

Fix for https://www.seblod.com/community/forums/forms-content-types/using-upload-image-with-php8-give-error
Tested on J3.10.11 / S3.22.3 / PHP 8.0.28

Fix null object on PHP8

---

plugins/cck_field/jform_rules/tmpl/form.php

The js code can not retrieve input & select values as per usergroup tabs have new IDs.
A fix with the correct tab name to let hte js code retrieve values and fill the data array to encode.

New tab names for permissions

---

plugins/cck_field/field_x/field_x.php

If not, raises an error on PHP 8(.1) website if fieldx is empty

Check if $value is an array before doing the count

---

plugins/system/cck/cck.php

params is a protected property of the Joomla menuitem object and has to be accessed through the getParams() method

Fix access error to params protected property

---

administrator/components/com_cck/assets/css/ui.css

Remove this padding to stay them from template. These paddings are too small.
This view WITHOUT paddings:
And this view WITH paddings:

Update ui.css remove paddings from .inputbox
