libraries/cms/cck/plugin/location.php

Also fix undefined $pk variable notice.

Fix for wrong author id due to multiple records with the same $pk

---

modules/mod_cck_search/tmpl/default.php

http://www.seblod.com/resources/tracker/1415

add missing parameters to search module when SEF is off

---

libraries/cck/base/list/list_inc.php
plugins/cck_storage_location/joomla_article/joomla_article.php

http://www.seblod.com/resources/tracker/12821

Fix routing issues on redirect

---

libraries/cck/rendering/rendering.php

Fix replaceLive()

---

libraries/cck/misc/Mobile_Detect.php

Added new Samsung tablets and other tablets requested by users.

Update "Mobile Detect" to 2.8.16

---

libraries/cck/misc/Mobile_Detect.php

Update "Mobile Detect" to 2.8.17

---

templates/seb_one/fields/_markup.php

Missing `$field->markup_class` in `_markup.php` file.

Update _markup.php in seb_one template

---

libraries/cms/cck/plugin/field.php
plugins/cck_field/text/text.php
plugins/cck_field/textarea/textarea.php

Enable translation of custom attributes using J(STRING) syntax in all fields that use them

Translate Custom attributes

---

plugins/cck_field/jform_tag/jform_tag.php

Fix search by article tags errors, fixes #37

fix article tags search, fixes #37

---

administrator/components/com_cck/install/upgrades/2.6.0.sql
libraries/cms/cck/dev.php

Birthdate/birthplace fix from Klas.

Merge dev to master

---

plugins/content/cck/cck.php

Allow article title change by using fields value after it was processed by beforeRender

allow title change from beforeRender

---

administrator/components/com_cck/_CHANGELOG.php
libraries/cck/misc/Mobile_Detect.php

Added Kindle, Asus, AOC tablets.
Added Nokia Lumia to the detection array because of Windows Continuum.

Update "Mobile Detect" to 2.8.22

---

plugins/cck_field_validation/email/email.php

fix email validation for new tlds, fixes #124

---

plugins/cck_field/jform_user/jform_user.php

Fix wrong url in modal and 0 always submitting issue

---

administrator/components/com_cck/config.xml

Reference http://www.seblod.com/community/forums/general-discussions/open-basedir-restriction-in-effect#post45009

change absolute path to relative to avoid open basedir and other issues

---

templates/seb_blog/index.php

Add loadmore class for ajax pagination loading
Reference
http://www.seblod.com/community/forums/templates-position-variations/as-in-masonry-to-implement-load-more#post43131

fix load more in blog

---

plugins/cck_field/42/42.php

Add missing id, fix notices

---

libraries/cck/base/list/list_inc.php

Fix errors and notices with cache activaed on rendering

---

administrator/components/com_cck/views/fields/tmpl/default.php
administrator/components/com_cck/views/folders/tmpl/default.php
administrator/components/com_cck/views/form/tmpl/select.php
administrator/components/com_cck/views/search/tmpl/edit2.php
administrator/components/com_cck/views/searchs/tmpl/default.php
administrator/components/com_cck/views/sessions/tmpl/default.php
administrator/components/com_cck/views/sites/tmpl/default.php
administrator/components/com_cck/views/templates/tmpl/default.php
administrator/components/com_cck/views/type/tmpl/edit2.php
administrator/components/com_cck/views/types/tmpl/default.php
administrator/components/com_cck/views/variations/tmpl/default.php
administrator/components/com_cck/views/versions/tmpl/default.php
libraries/cck/rendering/document/document.php
libraries/cck/rendering/rendering.php
libraries/cck/rendering/rendering_item.php
modules/mod_cck_breadcrumbs/mod_cck_breadcrumbs.php
modules/mod_cck_list/tmpl/default.php
plugins/cck_field/storage/storage.php
plugins/cck_field/upload_file/upload_file.php
plugins/cck_field/upload_image/upload_image.php
templates/seb_blog/index.php
templates/seb_one/index.php
templates/seb_table/index.php

`__DIR__` was introduced in PHP 5.3 ⚠️ 
`__DIR__ == dirname(__FILE__)` 😉

Replace dirname(__FILE__) with __DIR__ 

---

administrator/components/com_cck/_CHANGELOG.php
administrator/modules/mod_cck_menu/helper.php
libraries/cms/cck/dev/integration.php

The continuation of this #78 
😉 Because this...

Removed limit of characters

---

libraries/cms/cck/dev/image.php

Quality not use in library _generateThumb()
It's bug or not???

Parameters number mismatch declaretion

---

plugins/cck_field/calendar/calendar.php

Fix errors on calendar use in fieldX/groupX.
Fix errors with live value now/today etc in combination with hidden variation.

Fix Groupx/FieldX, fix variations

---

plugins/cck_field/calendar/calendar.php

Fix variations broken after 3.11.2 (hidden, value - hidden is not hidden at all)

Fix calendar variations

---

administrator/components/com_cck/_CHANGELOG.php
libraries/cck/misc/Mobile_Detect.php

Just an update of the "Mobile Detect" library.

Update "Mobile Detect" to 2.8.26

---

libraries/cck/base/list/list_inc.php

supersedes #19  (change target branch to master )

add beforeSearch event

---

plugins/cck_field/jform_calendar/jform_calendar.php

See https://github.com/Octopoos/SEBLOD/issues/581

Respect 'raw' storage of JForm - Calendar fields

---

administrator/components/com_cck/assets/css/admin.css
administrator/components/com_cck/views/fields/tmpl/default.php
administrator/components/com_cck/views/folders/tmpl/default.php
administrator/components/com_cck/views/searchs/tmpl/default.php
administrator/components/com_cck/views/sites/tmpl/default.php
administrator/components/com_cck/views/templates/tmpl/default.php
administrator/components/com_cck/views/types/tmpl/default.php
administrator/components/com_cck/views/types/tmpl/default_compact.php
administrator/components/com_cck/views/versions/tmpl/default.php

Move back-end table row height to CSS so that user can override it with custom CSS.

Move back-end table row height to CSS

---

language/en-GB/en-GB.files_var_cck_seb_css3.sys.ini
language/fr-FR/fr-FR.files_var_cck_seb_css3.sys.ini

Correct the inconsistent naming of the file in Extensions Manager.

Correct missing file name for seb_css3b

---

plugins/cck_storage_location/joomla_category/classes/helper.php
plugins/cck_storage_location/joomla_category/joomla_category.php

Fix association field display and store for categories

---

plugins/cck_storage_location/joomla_article/joomla_article.php

@sebastienheraud  With the 'error' param for appEnqueueMessage

Fix association field display and store for articles

---

libraries/cck/_/plugin/location.php

This fixes the creation of the User Bridge

Force $params to be set as static seems to have any effect
